[package]
name = "ic_siwb_provider"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.17"
ic-cdk = "0.18.7"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
lto = true
opt-level = 3
