[package]
name = "ic_siwb_provider"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.17"
ic-cdk = "0.18.7"
ic-cdk-macros = "0.18.7"
serde = { version = "1.0", features = ["derive"] }
k256 = { version = "0.13", features = ["ecdsa", "sha256"] }
sha2 = "0.10"
hex = "0.4"
getrandom = { version = "0.2", default-features = false, features = ["custom"] }

[profile.release]
lto = true
opt-level = 3
