[package]
name = "ic_siwb_provider"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.17"
ic-cdk = "0.18.7"
ic-cdk-macros = "0.18.7"
serde = { version = "1.0", features = ["derive"] }
bitcoin = "0.32"
secp256k1 = { version = "0.29", default-features = false, features = ["recovery"] }
sha2 = "0.10"
hex = "0.4"
rand = "0.8"
getrandom = { version = "0.2", default-features = false, features = ["js"] }

[profile.release]
lto = true
opt-level = 3
